title: Yuval Nirkin
description: > # this means to ignore newlines until "baseurl:"
  Yuval Nirkin's personal website.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /flexible-jekyll
url: "https://nirkin.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Yuval Nirkin # add your name
author-img: avatar.jpg # add your photo
about-author: Computer Vision & Deep Learning Researcher # add description
twitter: home # add your Twitter handle
facebook:  # add your Facebook handle
github: YuvalNirkin # add your Github handle
linkedin: ynirkin # add your Linkedin handle
#wordpress: shaoanlu
youtube: UC3jJoAIA1tXv3ZgKrNXalTg
email: yuval.nirkin@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
